
\c true
\p ******* DROP TABLE START *******

drop TABLE Screenshot;
drop TABLE TestCaseResult;

\p ******* DROP TABLE END *******

\p ******* DROP SEQUENCE START *******

drop SEQUENCE Seq_TestCaseResult;
drop SEQUENCE Seq_Screenshot;

\p ******* DROP SEQUENCE END *******

\c false

/* Create Sequences */
\p ******* CREATE SEQUENCE START *******

CREATE SEQUENCE Seq_TestCaseResult AS INTEGER START WITH 8;
CREATE SEQUENCE Seq_Screenshot AS INTEGER START WITH 22;

\p ******* CREATE SEQUENCE END *******

/* Create Tables */
\p ******* CREATE TABLE START *******

CREATE TABLE TestCaseResult
(
	id int GENERATED BY DEFAULT AS SEQUENCE Seq_TestCaseResult NOT NULL,
	executeTime varchar(19) NOT NULL UNIQUE,
	expectedId varchar(19),
	PRIMARY KEY (id)
);


CREATE TABLE Screenshot
(
	id int GENERATED BY DEFAULT AS SEQUENCE Seq_Screenshot NOT NULL,
	screenshotId varchar(20) NOT NULL,
	fileName varchar(250) NOT NULL,
	result boolean,
	testCaseResultId int NOT NULL,
	PRIMARY KEY (id)
);

\p ******* CREATE TABLE END *******


/* Create Foreign Keys */
\p ******* ALTER TABLE START *******

ALTER TABLE Screenshot
	ADD FOREIGN KEY (testCaseResultId)
	REFERENCES TestCaseResult (id)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

\p ******* ALTER TABLE END *******

