/* Create Sequences */

CREATE SEQUENCE Seq_Result AS INTEGER START WITH 10;
CREATE SEQUENCE Seq_Screenshot AS INTEGER START WITH 10;

/* Create Tables */

CREATE TABLE Result
(
	resultId int GENERATED BY DEFAULT AS SEQUENCE Seq_Result NOT NULL,
	executeTime varchar(19) NOT NULL UNIQUE,
	expectedId varchar(19),
	PRIMARY KEY (resultId)
);


CREATE TABLE Screenshot
(
	sid int GENERATED BY DEFAULT AS SEQUENCE Seq_Screenshot NOT NULL,
	screenshotId varchar(20) NOT NULL,
	fileName varchar(250) NOT NULL,
	comparisonResult boolean,
	resultId int NOT NULL,
	PRIMARY KEY (sid)
);



/* Create Foreign Keys */

ALTER TABLE Screenshot
	ADD FOREIGN KEY (resultId)
	REFERENCES Result (resultId)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


