/* Create Sequences */

CREATE SEQUENCE Seq_Target AS INTEGER START WITH 10;
CREATE SEQUENCE Seq_Result AS INTEGER START WITH 10;
CREATE SEQUENCE Seq_Screenshot AS INTEGER START WITH 10;
CREATE SEQUENCE Seq_CompareRule AS INTEGER START WITH 10;
CREATE SEQUENCE Seq_Capability AS INTEGER START WITH 10;

/* Create Tables */

CREATE TABLE Capability
(
	capabilityId int GENERATED BY DEFAULT AS SEQUENCE Seq_Capability NOT NULL,
	testClass varchar(20) NOT NULL,
	testMethod varchar(20) NOT NULL,
	platform varchar(20) NOT NULL,
	platformVersion varchar(10),
	browserName varchar(20) NOT NULL,
	browserVersion varchar(10),
	deviceName varchar(20),
	label varchar(200),
	PRIMARY KEY (capabilityId)
);


CREATE TABLE CompareOption
(
	optionId int NOT NULL,
	ruleId int NOT NULL,
	PRIMARY KEY (optionId)
);


CREATE TABLE CompareRule
(
	ruleId int GENERATED BY DEFAULT AS SEQUENCE Seq_CompareRule NOT NULL,
	ruleType int NOT NULL,
	result boolean,
	childRuleId int NOT NULL,
	sid int NOT NULL,
	PRIMARY KEY (ruleId)
);


CREATE TABLE Result
(
	resultId int GENERATED BY DEFAULT AS SEQUENCE Seq_Result NOT NULL,
	executeTime varchar(19) NOT NULL UNIQUE,
	expectedId varchar(19),
	PRIMARY KEY (resultId)
);


CREATE TABLE Screenshot
(
	sid int GENERATED BY DEFAULT AS SEQUENCE Seq_Screenshot NOT NULL,
	screenshotId varchar(20) NOT NULL,
	fileName varchar(250) NOT NULL,
	result boolean,
	capabilityId int NOT NULL,
	resultId int NOT NULL,
	PRIMARY KEY (sid)
);


CREATE TABLE Target
(
	targetId int GENERATED BY DEFAULT AS SEQUENCE Seq_Target NOT NULL,
	selector varchar(20) NOT NULL,
	selectorType int NOT NULL,
	x int NOT NULL,
	y int NOT NULL,
	width numeric(4,1) NOT NULL,
	height numeric(4,1) NOT NULL,
	ruleId int NOT NULL,
	PRIMARY KEY (targetId)
);



/* Create Foreign Keys */

ALTER TABLE Screenshot
	ADD FOREIGN KEY (capabilityId)
	REFERENCES Capability (capabilityId)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE Target
	ADD FOREIGN KEY (ruleId)
	REFERENCES CompareRule (ruleId)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CompareRule
	ADD FOREIGN KEY (childRuleId)
	REFERENCES CompareRule (ruleId)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CompareOption
	ADD FOREIGN KEY (ruleId)
	REFERENCES CompareRule (ruleId)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE Screenshot
	ADD FOREIGN KEY (resultId)
	REFERENCES Result (resultId)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CompareRule
	ADD FOREIGN KEY (sid)
	REFERENCES Screenshot (sid)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



