/* Create Sequences */

CREATE SEQUENCE Seq_TestCaseResult AS INTEGER START WITH 8;
CREATE SEQUENCE Seq_Screenshot AS INTEGER START WITH 22;

/* Create Tables */

CREATE TABLE TestCaseResult
(
	id int GENERATED BY DEFAULT AS SEQUENCE Seq_TestCaseResult NOT NULL,
	executeTime varchar(19) NOT NULL UNIQUE,
	expectedId varchar(19),
	PRIMARY KEY (id)
);


CREATE TABLE Screenshot
(
	id int GENERATED BY DEFAULT AS SEQUENCE Seq_Screenshot NOT NULL,
	screenshotId varchar(20) NOT NULL,
	fileName varchar(250) NOT NULL,
	result boolean,
	testCaseResultId int NOT NULL,
	PRIMARY KEY (id)
);



/* Create Foreign Keys */

ALTER TABLE Screenshot
	ADD FOREIGN KEY (testCaseResultId)
	REFERENCES TestCaseResult (id)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


